[package]
name = "wasi-worker"
version = "0.3.0"
authors = ["Maksym Vorobiov <maxim.vorobjov@gmail.com>"]
edition = "2018"
license = "MIT"
description = "WASM/WASI interface for browser service workers"
readme = "README.md"
keywords = ["wasi", "wasm", "service worker", "worker"]
categories = ["web-programming", "webassembly"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
